import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { FLEET } from "../lib/data";

export default function HelicoptersPage() {
  const router = useRouter();
  const helicopters = FLEET.filter(v => v.type === "helicopter");

  return (
      <div className="min-h-screen bg-[#020617] text-white">
            <Head>
                    <title>Helicopter Fleet | Nocturnal Atelier</title>
                            <meta charSet="utf-8" />
                                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                                          </Head>
                                          
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#020617]/95 backdrop-blur-xl border-b border-white/10 px-6 lg:px-12 py-4">
              <div className="max-w-7xl mx-auto flex items-center justify-between gap-6">
                        <Link href="/" className="text-2xl font-serif tracking-tight text-[#e9c176]">
                                    AERIS
                                              </Link>
                                                        <div className="hidden md:flex items-center gap-10 text-sm text-slate-300">
                                                                    <Link href="/fleet" className="hover:text-white transition">Private Jets</Link>
                                                                                <Link href="/helicopters" className="text-[#e9c176] font-semibold hover:text-white transition">Helicopters</Link>
                                                                                            <Link href="/ambulance" className="hover:text-white transition">Air Ambulance</Link>
                                                                                                        <Link href="/yachts" className="hover:text-white transition">Destinations</Link>
                                                                                                                  </div>
                                                                                                                            <Link href="/ambulance" className="whitespace-nowrap rounded-full bg-[#e9c176] px-5 py-2 text-xs font-semibold uppercase tracking-[0.35em] text-slate-950 hover:bg-[#ffd87f] transition">
                                                                                                                                        Inquire Now
                                                                                                                                                  </Link>
                                                                                                                                                          </div>
                                                                                                                                                                </nav>
                                                                                                                                                                
      <main className="pt-28 pb-16 px-6 lg:px-12 max-w-7xl mx-auto">
              <section className="mb-16">
                        <div className="flex flex-col lg:flex-row justify-between gap-10 border-b border-white/10 pb-12">
                                    <div className="max-w-2xl">
                                                  <p className="uppercase tracking-[0.35em] text-sm text-[#e9c176] mb-4">Fleet Directory</p>
                                                                <h1 className="text-5xl lg:text-6xl font-serif leading-tight">
                                                                                Urban Mobility:
                                                                                                  <br />
                                                                                                                  <span className="italic font-light text-white">The Helicopter Collection</span>
                                                                                                                                </h1>
                                                                                                                                              <p className="mt-6 max-w-xl text-slate-300 leading-8">
                                                                                                                                                              Explore our premium helicopter fleet for executive transfers, luxury events, and fast-response travel. Each model is curated for comfort, performance, and unforgettable arrival experiences.
                                                                                                                                                                            </p>
                                                                                                                                                                                        </div>
                                                                                                                                                                                                    <div className="flex flex-col justify-between rounded-3xl border border-white/10 bg-white/5 p-8 shadow-xl shadow-black/20 max-w-sm">
                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                  <p className="text-xs uppercase tracking-[0.35em] text-slate-400 mb-6">Precision Engineering</p>
                                                                                                                                                                                                                                                  <p className="mt-4 text-3xl font-semibold text-[#e9c176]">12 Available Models</p>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                              <div className="mt-8 space-y-3 text-sm text-slate-300">
                                                                                                                                                                                                                                                                                              <p>Helicopters for scenic flights, VVIP transfers, and versatile utility missions.</p>
                                                                                                                                                                                                                                                                                                              <p>Instant global support with dedicated concierge dispatch.</p>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                          
        <div className="grid gap-10 lg:grid-cols-[280px_minmax(0,1fr)]">
                  <aside className="space-y-10 rounded-3xl border border-white/10 bg-white/5 p-8 shadow-xl shadow-black/15">
                              <div>
                                            <h2 className="text-xs uppercase tracking-[0.35em] text-[#e9c176] mb-6">Configuration</h2>
                                                          <div className="space-y-4 text-sm text-slate-300">
                                                                          <label className="flex items-center gap-3">
                                                                                            <input type="checkbox" className="h-4 w-4 accent-[#e9c176] text-[#e9c176]" />
                                                                                                              Single Engine
                                                                                                                              </label>
                                                                                                                                              <label className="flex items-center gap-3">
                                                                                                                                                                <input type="checkbox" defaultChecked className="h-4 w-4 accent-[#e9c176] text-[#e9c176]" />
                                                                                                                                                                                  Twin Engine
                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                            
            <div>
                          <h2 className="text-xs uppercase tracking-[0.35em] text-[#e9c176] mb-6">Mission Range</h2>
                                        <div className="space-y-3">
                                                        <input type="range" min="100" max="1000" step="50" className="w-full accent-[#e9c176]" />
                                                                        <div className="flex justify-between text-[11px] uppercase tracking-[0.25em] text-slate-500">
                                                                                          <span>100 km</span>
                                                                                                            <span>1000+ km</span>
                                                                                                                            </div>
                                                                                                                                          </div>
                                                                                                                                                      </div>
                                                                                                                                                      
            <div>
                          <h2 className="text-xs uppercase tracking-[0.35em] text-[#e9c176] mb-6">Advanced Tech</h2>
                                        <div className="rounded-3xl border border-white/10 bg-[#0f172a] p-4 flex items-center justify-between gap-4">
                                                        <span className="text-sm text-slate-300">Quiet Technology</span>
                                                                        <span className="inline-flex h-6 w-12 items-center rounded-full bg-slate-800 p-1">
                                                                                          <span className="h-4 w-4 rounded-full bg-[#e9c176]" />
                                                                                                          </span>
                                                                                                                        </div>
                                                                                                                                      <p className="mt-3 text-[13px] leading-6 text-slate-400">
                                                                                                                                                      Select the quietest fleet equipped with BlueEdge rotors and vibration reduction systems.
                                                                                                                                                                    </p>
                                                                                                                                                                                </div>
                                                                                                                                                                                
            <button className="w-full rounded-full border border-white/10 bg-white/5 px-6 py-4 text-xs uppercase tracking-[0.35em] text-slate-300 hover:bg-white/10 transition">
                          Reset Filters
                                      </button>
                                                </aside>
                                                
          <section className="space-y-8">
                      {helicopters.map((vehicle) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <article key={vehicle.id} className="group overflow-hidden rounded-[2rem] border border-white/10 bg-[#0f172a] shadow-xl shadow-black/20 transition hover:-translate-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="relative overflow-hidden aspect-[16/10]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={vehicle.image} alt={vehicle.model} className="h-full w-full object-cover transition duration-1000 group-hover:scale-110" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.badge ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="absolute top-5 left-5 rounded-full bg-[#e9c176] px-3 py-1 text-[11px] font-semibold uppercase text-slate-950">{item.badge}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-[#020617] via-transparent to-transparent" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="p-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-start justify-between gap-4 mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 className="text-2xl font-serif">{vehicle.model}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs uppercase tracking-[0.35em] text-slate-400 mt-1">{vehicle.cabinClass}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs uppercase tracking-[0.35em] text-[#e9c176] font-semibold">€{vehicle.price_per_hour}/hr</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-[10px] text-slate-500 uppercase tracking-[0.4em] mt-1">Charter Rate</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-3 gap-4 border-y border-white/10 py-6 mb-8 text-sm text-slate-300">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-[10px] uppercase tracking-[0.35em] text-slate-500">Capacity</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="mt-2 font-semibold text-white">{vehicle.passenger_capacity} Pax</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-[10px] uppercase tracking-[0.35em] text-slate-500">Cruise</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-2 font-semibold text-white">{vehicle.speed}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-[10px] uppercase tracking-[0.35em] text-slate-500">Range</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="mt-2 font-semibold text-white">{vehicle.range}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => router.push('/checkout?vehicle_id=' + vehicle.id)} className="w-full rounded-full bg-[#e9c176] py-4 text-xs font-semibold uppercase tracking-[0.35em] text-slate-950 transition hover:bg-[#ffd87f]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Reserve Flight
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      <div className="fixed bottom-8 right-8 z-40 rounded-full bg-[#111827]/95 p-4 shadow-2xl shadow-black/25 backdrop-blur-xl border border-white/10">
              <div className="flex items-center gap-3">
                        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#e9c176] text-[#020617]">
                                    <span className="material-symbols-outlined">support_agent</span>
                                              </div>
                                                        <div>
                                                                    <p className="text-[10px] uppercase tracking-[0.35em] text-[#e9c176] font-semibold">Concierge Live</p>
                                                                                <p className="text-xs text-slate-300">Fleet Specialist Online</p>
                                                                                          </div>
                                                                                                  </div>
                                                                                                        </div>
                                                                                                        
      <footer className="bg-[#020617] border-t border-white/10 py-12 px-6">
              <div className="max-w-7xl mx-auto flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
                        <p className="text-xs uppercase tracking-[0.35em] text-slate-500">© 2024 Obsidian Reserve. The Art of Arrival.</p>
                                  <div className="flex flex-wrap gap-4 text-xs uppercase tracking-[0.25em] text-slate-500">
                                              <a href="#" className="hover:text-[#e9c176] transition">Charter Terms</a>
                                                          <a href="#" className="hover:text-[#e9c176] transition">Privacy Policy</a>
                                                                      <a href="#" className="hover:text-[#e9c176] transition">Fleet Specifications</a>
                                                                                  <a href="#" className="hover:text-[#e9c176] transition">Global Logistics</a>
                                                                                              <a href="#" className="hover:text-[#e9c176] transition">Member Login</a>
                                                                                                        </div>
                                                                                                                </div>
                                                                                                                      </footer>
                                                                                                                          </div>
                                                                                                                            );
                                                                                                                            }
                                                                                                                            